sudo: false
env:
    - PEARLBEE_DATABASE_CONFIG: "TRAVIS_DATABASE"
services:
    - postgresql
language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
before_script:
    - psql -c 'CREATE DATABASE pearlbee; CREATE SCHEMA pearlbee;' -U postgres
    - perl ./bin/deploy-schema TRAVIS_DATABASE
    - perl ./bin/load-initial-data TRAVIS_DATABASE
