sudo: false
addons:
  apt:
    packages:
      - libgd-dev
env:
    - DANCER_ENVIRONMENT: "travis"
services:
    - postgresql
language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
before_script:
    - psql -c 'CREATE DATABASE pearlbee' -U postgres
    - psql -c 'CREATE SCHEMA pearlbee' -U postgres pearlbee
    - perl ./bin/deploy-schema TRAVIS_DATABASE
    - perl ./bin/load-initial-data TRAVIS_DATABASE
script:
    - perl -Ilib -MData::Dumper -MPearlBee -e 'print Dumper(PearlBee::config())'
    - prove -rvl t
