# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "PearlBee"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"


# template engine
# simple: default and very basic template engine
# template_toolkit: TT

session: "YAML"

#Logging
#logger: "file"
#log: "error"
template: "Handlebars"
engines:
  template:
    template_toolkit:
      extension: 'tt'
      encoding: 'utf8'
      start_tag: '[%'
      end_tag:   '%]'
    Handlebars:
      path:
        - themes/casper
        - themes/casper/partials
        - views
      verbose: 1
  session:
    YAML:
      session_dir: "/tmp/pearlbee"

plugins:
    Mailer::PearlBee:
        from:  'The PearlBee Team <no-reply@pearlbee.com>'
    DBIC:
        default:
            dsn: DEFAULT_DATABASE
            schema_class: 'PearlBee::Model::Schema'
    Auth::PearlBee:
        permissions:
            author:
                can:
                  - view_post
                  - create_post
                  - publish_post
                  - update_post
                  - delete_post
                  - view_category
                  - create_category
                  - update_category
                  - delete_category
                  - view_comment
                  - update_comment
                  - view_tag
                  - update_tag
                  - delete_tag
                  - view_setting
                  - update_setting
            limited_author:
                all_from:
                  - author
                except:
                  - publish_post
            admin:
                all_from:
                  - author
                can:
                  - global_settings
                  - view_user
                  - create_user
                  - update_user
                  - delete_user
                  - allow_user
                  - import

comments: disqus
comments_engines:
    disqus:
        shortname: mydisqusshortname

# Constants
captcha_folder :  'public/captcha/'
covers_folder:    'public/uploads/covers/'
import_folder:    'public/uploads/import/'
images_folder:    'public/uploads/images/'
images_path:      '/uploads/images'
timezone:         'Europe/Amsterdam'
blog_name:        'PearlBee'
theme_folder:     'views/themes/'

# Specifics
posts_on_page:         5
captcha_enabled:       0 # use 1 to enable captchas

site:
  name:    "blogs.perl.org"
  tagline: "There's more than one way to blog it"
  logo:    "/images/camel-silhouette-white.png"
