= User Journey with Pearlbee
André Walker <andre@andrewalker.net>

== Abstract

This document describes the different actors that interact with Pearlbee, and
what they expect to see and be able to do. It's meant for me to be a kind of
completion criteria as I develop the software.

== Actors

I'm mainly interested in four actors at this point:

- The Reader
- The Author
- The Site Administrator
- The Theme Developer

The rest of this document will go into detail of what each of those will be
able to do. In other words, what features the platform is expected to provide
each of them.

The journey is expressed in terms of a multi-user blogging installation, as my
goal is to use it for blogs.perl.org. It probably wouldn't be much different
for a single-user blog, only simpler.

Some possible users of the platform are not listed above, because they are not
my primary concern at the moment. They are still relevant and should be taken
into account as the platform matures. Some examples:

- Robots -- I'll just treat them as Readers for now, which is fine for an MVP,
  but will require more care later on. (Not that I would make multiple versions
  of the website, but that I would think of bots use cases and implement
  features they require)
- Editors -- Powerful Author that can also edit other peoples' posts.
- Extension Developers -- we will have to provide some sort of engine for
  extensions, but for now, I'll only offer a working core.

Probably some others, but let's begin with the list we're mostly concerned.

== The Reader

A visitor comes to the homepage, they see a list of recent posts. For now, let's
say it's only sorted by date, most recent to oldest, among all authors. Only
some brief information is shown about every post: title, author, date it was
published and abstract. Clicking on the post takes the Reader to a page showing
the full post.

From the homepage, a search bar is visible where the user can search by keyword.
Somewhere else in the website, there should be a way to do an advanced search:
by author, by keyword, by date, by tag.

Still in the home page, it will be possible to click author names (from the list
of recent posts, at least), which will take the Reader to an author page. That
will be like the author's own blog: it will list their recent posts, an avatar,
a bio, links to social media, etc. It will not include a different layout
though, it will be consistent with the rest of the website.

That author page will also have an easy to remember URI, just "/:username". This
way it can be easily bookmarked or shared. It will likely be a common
entry point to the website, besides the homepage.

The Reader can also subscribe to RSS feeds for the entire blog (all the authors)
or for specific authors.

The Reader will be able to become an author by registering in the platform.
Every registered user will be able to write. Registering will provide no
additional features for readers at this point (there won't be a "follow" feature
as far as I can see). Not even comments, since it will be provided by a
third-party on a first moment (e.g. Disqus).

== The Author

As stated above, to become an Author, one would have to register on Pearlbee.
The process consists of filling out a short form, with email, username (only as
a handle for the URI) and password. The author would then need to verify the
email by clicking a link.

Now, when I say "Author" I'm actually grouping multiple actors together. As soon
as an Author gets registered, they are in fact an _Unconfirmed Author_. That
means they can write a post, but it won't be published right away. Some of the
other authors will have to _confirm_ that post, so that it is effectively
published. This is to avoid spam, since using CAPTCHA and verifying email are
not 100% effective.

To elaborate a little more: the Author submits the registration form, clicks the
link on their email, and writes a post. That Author can see their own post, but
it is not publicly displayed on the homepage, or for unauthenticated Readers.
Only other Authors will see it in their dashboards, in a dedicated section to
review posts by unconfirmed authors.

TODO: Should everyone get a notification to confirm new posts? Should there be
a settings toggle per user where they can subscribe by email for that? Or just
show a small number on a menu for users that are logged in, and don't tell
anybody by email?

Once an Author is confirmed, they can write as many posts as they'd like. (We
should still have some DDoS protection though).

When an Author author logs into the dashboard, what they see is:

- a link to edit their _Profile_: avatar, bio, social media links. Change email
  (requires verifying again), and change password;
- a link to list their posts: there they can remove or edit them;
- a link to write a new post;
- _(only confirmed authors)_ a link to see the list of unconfirmed posts, and
  approve or reject them;

There have been suggestions to make "write new post" page the first one they see
when they log in, instead of the traditional "post list". Doesn't matter much,
but might as well be.

The list of posts will be sortable per publication date, ascending or
descending, and filterable per tag or keyword. Next to every post will be links
to update it or delete it. No actions will be destructive on the database level
though.

When writing the post, the Author will be presented with a simple WYSIWYG
editor, and it will be saved in Markdown for the time being. No other formats
will be supported at this time. The Author will also be able to write an
abstract for the post, to add a "cover image" for it, add a title, and tags.

When saving it, they will be able to publish right away or save as draft.

No guarantees will be made at this point regarding autosaving as draft. It would
be nice to have, but I'll focus on other basic features for now.

Regarding the confirmation of new authors, maybe we can start with the simplest
possible process, which is: a list of posts, similar to the list of the Author's
own posts. Next to that list, two links: thumbs down and thumbs up (or something
equivalent). One approval makes the new Author be _confirmed_, while one
rejection makes it _banned_.

I don't think it's a very robust process, but it should be enough for the MVP.
The idea is to work towards an implementation that requires little to no
maintenance from the Site Administrator, and engages participation of Authors.
If this eventually turns into a system where the platform knows which Authors
are trustworthy, and asks for multiple confirmations when in doubt, would be
very nice. Apparently Facebook does that for groups.

I also mentioned an Author can be _banned_. That can come from either other
Author rejecting their first post, or the Site Administrator banning them. Once
an Author is banned, only the Site Administrator can _unban_ them. A banned
Author is one whose posts are hidden, and cannot approve other Authors.

A final note about Authors: they are not editors. As specified above, they can
only update their own posts, never from other people.

== The Site Administrator

The Site Administrator is responsible for installing the Pearlbee platform,
upgrading it, performing general maintenance tasks.

Let's begin with installation. The Site Administrator will download a built
version of Pearlbee (ideally something like an rpm or deb), and install it
according to their distribution. It can also be from CPAN. In fact, I'm
differentiating the built version from the source version mainly with regards
with static assets (js, css, images, etc). There will likely be a build step
to take the git version and turn it into the deployment version to be shipped to
CPAN.

It can be installed globally in the system, or using tools like local\::lib,
carton, perlbrew, etc. The most important thing is that the Pearlbee package
will remain separate from the site-specific theme and configuration.

Pearlbee will come with a core theme, and to pick a different one, the Site
Administrator will have to specify a command line argument with the path to the
theme they want to use.

Most of the configuration will be specified in a configuration file, also kept
outside of the Pearlbee package. That will include credentials for database,
site name, credentials for external services (e.g. Disqus), SMTP configuration,
etc.

The upgrade process will consist of upgrading the package and calling `sqitch
deploy` (or a wrapper around it).

The Site Administrator will also have a sort of _root_ user in the Pearlbee
interface. It will be similar to the Author interface, but they will have access
to everything.

On that dashboard they will be able to _confirm_, _ban_ and _unban_ any Author,
delete and update posts.

_(Maybe the dashboard one could be a different actor from the "command line
one"?)_

== The Theme Developer

TODO.
